/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;
import utils.PrincipalMetodos;

/**
 *
 * @author PRR1TL
 */
public class CargaTargets extends javax.swing.JFrame {

    /**
     * Creates new form CargaTargets
     */
    
    public static String linea = "";
    public static String mes = "";
    public static String anio = "";
    public static String noMes = "";
    public static String mes2 = "";
    
    String dias;
    String tek;
    String programado;
    String[] arrayNombres;    
        
    String dia = ""; 
    
    String metaTec;
    String metaOrg;
    String metaCalidad;
    String metaScrap;
    String metaCambios;
    String metaPlaneados;
    
    int existe = 0 ;
    
    
    public CargaTargets() {
        initComponents();
        
        Calendar cal = Calendar.getInstance(); 
        String anioAc = Integer.toString(cal.get(Calendar.YEAR));
        String anioAnt = Integer.toString(cal.get(Calendar.YEAR) - 1);
        String anioPos = Integer.toString(cal.get(Calendar.YEAR) + 1);
       
        String labels[] = { anioAnt, anioAc, anioPos,};
        
        //System.out.println(anioAnt+" "+anioAc+" "+anioPos);
        
        cmbLinea.setModel(new PrincipalMetodos().listaLineas());
        cmbAnio.addItem("Seleona Año");
        cmbAnio.addItem(anioAnt);
        cmbAnio.addItem(anioAc);
        cmbAnio.addItem(anioPos);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbLinea = new javax.swing.JComboBox<>();
        cmbMes = new javax.swing.JComboBox<>();
        cmbAnio = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbLinea.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbLineaItemStateChanged(evt);
            }
        });

        cmbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona Mes", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        cmbMes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbMesItemStateChanged(evt);
            }
        });

        cmbAnio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbAnioItemStateChanged(evt);
            }
        });

        btnGuardar.setText("Cargar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel1.setText("Linea: ");

        jLabel2.setText("Año: ");

        jLabel3.setText("Mes: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Carga de Targets");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnGuardar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbMesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbMesItemStateChanged
        // TODO add your handling code here:
        if(cmbMes.getSelectedIndex() == 0){
            cmbAnio.setEnabled(false);
        } else {
            cmbAnio.setEnabled(true);
        }        
    }//GEN-LAST:event_cmbMesItemStateChanged

    private void cmbAnioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbAnioItemStateChanged
        if(cmbLinea.getSelectedIndex() != 0){
            btnGuardar.setEnabled(true);
        } else {
            btnGuardar.setEnabled(false);
        }
    }//GEN-LAST:event_cmbAnioItemStateChanged

    private void cmbLineaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbLineaItemStateChanged
        if(cmbLinea.getSelectedIndex() != 0){
            cmbMes.setEnabled(true);
        } else {
            cmbMes.setEnabled(false);
        }
    }//GEN-LAST:event_cmbLineaItemStateChanged

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        linea = cmbLinea.getSelectedItem().toString();
        mes = cmbMes.getSelectedItem().toString();
        noMes = Integer.toString(cmbMes.getSelectedIndex());
        anio = cmbAnio.getSelectedItem().toString();
        
        //System.out.println(linea+' '+mes+' '+noMes+' '+anio);
        
        int cargaM = JOptionPane.showConfirmDialog(null, "¿Desea Cargar Targets de Entregas?\n\t"+ linea,  "Mensaje", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
      
        if (cargaM == 0) {
            File file = new File("C:\\Users\\PRR1TL.SG\\Documents\\Formatos\\Targets.xls");
            try {
                obtencionFecha(file);                
            } catch (IOException ex) {
                Logger.getLogger(CargaTargets.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(CargaTargets.class.getName()).log(Level.SEVERE, null, ex);
            }
        }   
    }//GEN-LAST:event_btnGuardarActionPerformed

    public void obtencionFecha(File file) throws IOException, Exception{
        int ban = 0;
        dao.CargaTargetEntregas cargaObj = new dao.CargaTargetEntregas();
        Workbook workbook = null;   
        ArrayList regDia;
        ArrayList regTEK;
        ArrayList regProg;
        ArrayList regScrap;
        ArrayList regTecnicas ;
        ArrayList regOrg; 
        ArrayList regCalidad; 
        ArrayList regCambios; 
        ArrayList regPlaneados;
        
        try {
            workbook = Workbook.getWorkbook(file);
            Sheet sheet = workbook.getSheet(0);     
            regDia = new ArrayList();
            regTEK = new ArrayList();
            regProg = new ArrayList();
            regTecnicas = new ArrayList();
            regOrg = new ArrayList();
            regCalidad = new ArrayList();
            regScrap = new ArrayList();
            regCambios = new ArrayList();
            regPlaneados = new ArrayList();
            
            for (int i = 1; i < sheet.getColumns()-1; i++) { //determina cuantas columnas va agarrar 
                jxl.Cell cellDia = sheet.getCell(i, 3); //num,
                jxl.Cell cellTEK = sheet.getCell(i, 5);
                jxl.Cell cellProg = sheet.getCell(i, 6);                  
                //Perdidas
                jxl.Cell cellTec = sheet.getCell(i, 19); //num,
                jxl.Cell cellOrg = sheet.getCell(i, 25); 
                jxl.Cell cellCalidad = sheet.getCell(i, 31); 
                jxl.Cell cellScrap = sheet.getCell(i, 37);
                jxl.Cell cellCambios = sheet.getCell(i, 43); 
                jxl.Cell cellPlaneados = sheet.getCell(i, 49);
                

                dias = cellDia.getContents();
                tek = cellTEK.getContents(); 
                programado = cellProg.getContents(); 
                metaTec = cellTec.getContents();
                metaOrg = cellOrg.getContents();
                metaCalidad = cellCalidad.getContents();
                metaScrap = cellScrap.getContents();
                metaCambios = cellCambios.getContents();
                metaPlaneados = cellPlaneados.getContents();

                regDia.add(cellDia.getContents());
                regTEK.add(cellTEK.getContents());
                regProg.add(cellProg.getContents()); 
                //PERDIDAS
                regTecnicas.add(cellTec.getContents());
                regOrg.add(cellOrg.getContents());
                regCalidad.add(cellCalidad.getContents()); 
                regScrap.add(cellScrap.getContents());
                regCambios.add(cellCambios.getContents()); 
                regPlaneados.add(cellPlaneados.getContents());

                arrayNombres = dias.split("-");

                for (int n = 0; n < arrayNombres.length-1; n++) {
                    if (n == 0) {
                        existe = 0;  
                        dia = arrayNombres[n].toUpperCase();
                        existe = cargaObj.consultaFechaExistente(linea, anio, noMes, dia);
                        if (existe == 0 ) {
                            cargaObj.insertarFechaYLinea(linea, anio, noMes, dia, tek, programado, metaTec, metaOrg, metaCalidad, metaScrap,metaCambios,metaPlaneados);
                            ban = 1;
                        } else  if (existe == 1 ){  
                            noMes = String.valueOf(Integer.parseInt(noMes)+1); 
                            if (noMes == "12") {            
                                cargaObj.insertarFechaYLinea(linea, String.valueOf(Integer.parseInt(anio)+1), noMes, dia, tek, programado, metaTec, metaOrg, metaCalidad, metaScrap,metaCambios,metaPlaneados); 
                                ban = 1;
                            } else {                                                              
                                cargaObj.insertarFechaYLinea(linea, anio, noMes, dia, tek, programado, metaTec, metaOrg, metaCalidad, metaScrap,metaCambios,metaPlaneados);
                                ban = 1;
                            }
                        }
                    }                         
                }                   
            }
            
            if (ban == 1){
                JOptionPane.showMessageDialog(null, "Datos cargados correctamente");
            }
            else {
                JOptionPane.showMessageDialog(null, "Los Datos NO fueron cargados. Favor de revisarlos");
            }
            
            System.out.println("regDia: "+regDia);
            System.out.println("regTek: "+regTEK);
            System.out.println("regPzasProg: "+regProg);
            
            System.out.println("regTec: "+regTecnicas);
            System.out.println("regOrg: "+regOrg);
            System.out.println("regCal: "+regCalidad);
            System.out.println("regScrap: "+regScrap);
            System.out.println("regCambios: "+regCambios);
            System.out.println("regPlaneados: "+regPlaneados);
            
            
        } catch (BiffException e) {
            e.printStackTrace();
        }
    }
       
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CargaTargets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CargaTargets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CargaTargets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CargaTargets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CargaTargets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbAnio;
    private javax.swing.JComboBox<String> cmbLinea;
    private javax.swing.JComboBox<String> cmbMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
