/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.PrincipalControl;
import dao.ConsultaPorTurnoDAOImpl;
import java.awt.Cursor;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import utils.PrincipalMetodos;
import static vista.TiempoTurno.cmbTiempoModel;

/**
 *
 * @author PRR1TL
 */
public class SelecTurno extends javax.swing.JDialog {
    private final PrincipalMetodos principalMetodos = new PrincipalMetodos();
    private  final Principal winPrincipal;
    public static String seleccionTurnoLinea = "";
    public static String fecha = "";
    
    private static ConsultaPorTurnoDAOImpl consultaTurno = new ConsultaPorTurnoDAOImpl();
    
    public static String turno = "";
    public static int inicioTurno = 0;
    public static int finTurno = 0;
    
    public static int bnLinea = 0;
    
    public SelecTurno(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        winPrincipal = (Principal) parent;
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/bs.png")).getImage());
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbTurno = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.setNextFocusableComponent(btnCancelar);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Selecciona Turno");

        cmbTurno.setNextFocusableComponent(btnAceptar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(44, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar)
                        .addGap(63, 63, 63))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        setCursor(new Cursor(Cursor.WAIT_CURSOR));
        cmbTurno.setEnabled(false);
        btnAceptar.setEnabled(false);
        btnCancelar.setEnabled(false);
        
        if((cmbTurno.getSelectedIndex() == 0)){
           JOptionPane.showMessageDialog(this, "Debes seleccionar un turno");
           bnLinea = 0;
           turno = "";
        }else{
            if (seleccionTurnoLinea != null){
                turno = cmbTurno.getSelectedItem().toString();
                try {
                    winPrincipal.getCmbHora().setModel(new DefaultComboBoxModel());
                    inicioTurno = consultaTurno.consultaInicioTurno(fecha, seleccionTurnoLinea,turno);
                    finTurno = consultaTurno.consultaFinTurno(fecha, seleccionTurnoLinea, turno);
                    principalMetodos.consultarBitacoraPorTurno(winPrincipal); 
                    winPrincipal.getMniOperaciones().setEnabled(true);
                    
                    winPrincipal.getCmbHora().removeAllItems();
                    
                    winPrincipal.getLblTurno().setText(turno + " <> " + inicioTurno + " - " + finTurno);
                    
                    if (inicioTurno > finTurno) {
                        //winPrincipal.getCmbHora().removeAllItems();
                        cmbTiempoModel.clear();
                        cmbTiempoModel.add("Selecciona Hora");
                        for (int i = inicioTurno; i != 0; i++) {
                            if (i == 24) {
                                i = 0;
                            } else if (i == finTurno) {
                                break;
                            }
                            cmbTiempoModel.add(i);
                        }
                    } else {
                        //winPrincipal.getCmbHora().removeAllItems();
                        cmbTiempoModel.clear();
                        int duracionTurno = finTurno - inicioTurno;
                        cmbTiempoModel.add("Selecciona Hora");
                        for (int i = 0, j = inicioTurno; i < duracionTurno; i++, j++) {
                            cmbTiempoModel.add(j);
                        }
                    }
                    winPrincipal.getCmbHora().setModel(new DefaultComboBoxModel(cmbTiempoModel.toArray()));
                    
                } catch (Exception ex) {
                    Logger.getLogger(SelecTurno.class.getName()).log(Level.SEVERE, null, ex);
                }
                dispose();
            } else {
                JOptionPane.showMessageDialog(this,"Debes elegir una linea, para poder hacer la edicion");
            }
            winPrincipal.getBtnCambiarLinea().setEnabled(false);
            winPrincipal.getCmbTema().setEnabled(true);
        }  
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        fecha = PrincipalControl.fecha;
        seleccionTurnoLinea = PrincipalControl.linea;
        try {
            cmbTurno.setModel(new ConsultaPorTurnoDAOImpl().listaTurnos(fecha, seleccionTurnoLinea));
        } catch (Exception ex) {
            Logger.getLogger(SelecTurno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cmbTurno.setSelectedIndex(0);
        winPrincipal.getLblTurno().setText(" ");
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (turno.equals("")) {
            new PrincipalMetodos().cancelarEdicion(winPrincipal);
        }
    }//GEN-LAST:event_formWindowClosing

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cmbTurno;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
