/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jxl.Cell;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;

/**
 *
 * @author PRR1TL
 */
public class CargaMClientes extends javax.swing.JFrame {

    private static DefaultTableModel modelo;
    dao.CargaMClientesDAOImpl cargaObj = new dao.CargaMClientesDAOImpl();
    
    /**
     * Creates new form CargaMClientes
     */
    public CargaMClientes() {
        initComponents();
        modelo = new DefaultTableModel();
        modelo.addColumn("Cliente");
        tblClientes.setModel(modelo);   
        importarExcel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente"
            }
        ));
        jScrollPane1.setViewportView(tblClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int columnas = tblClientes.getColumnCount();
        ArrayList reg;
        for (int i = 1; i < tblClientes.getRowCount(); i++) { //tomamos despues del encabezado 
            try {
                reg = new ArrayList();
                for (int j = 0; j < columnas; j++) {
                    reg.add(tblClientes.getValueAt(i, j));
                }
                System.err.println("."+reg);
                cargaObj.insertarCliente(reg);
            } catch (Exception ex) {
                Logger.getLogger(CargaMPerdidas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        limpiarTabla((DefaultTableModel) tblClientes.getModel());
        JOptionPane.showMessageDialog(null, "Clintes guardadas Correctamente",
               "Guardar", JOptionPane.INFORMATION_MESSAGE);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public void importarExcel (){
        //fileChooser.showDialog(null, "Importar Hoja ");
        //File file = fileChooser.getSelectedFile();
        File file = new File("C:\\Users\\PRR1TL\\Documents\\Clientes.xls");
        
        if (file.getName().endsWith("xls") || file.getName().endsWith("xlsx")) {
            try {
                crearTabla(file);
            } catch (IOException ex) {
                Logger.getLogger(CargaMPerdidas.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un archivo excel...", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void crearTabla(File file) throws IOException {
        Workbook workbook = null;

        try {
            workbook = Workbook.getWorkbook(file);
            Sheet sheet = workbook.getSheet(0);
            
            for (int j = 0; j < sheet.getRows(); j++) { //contador para agarrar la primer linea, determina cuantas filas va agarrar
                Vector d = new Vector();
                for (int i = 0; i < 1 ; i++) { //determina cuantas columnas va agarrar 
                    Cell cell = sheet.getCell(i, j);
                    d.add(cell.getContents());
                    //d.addElement("num Linea");
                }
                //System.err.println("-"+d);
                d.add("\n");
                //filas.add(d);
                modelo.addRow(d);
            }

        } catch (BiffException e) {
            e.printStackTrace();
        }
    }
    
    private void limpiarTabla(DefaultTableModel tableCarga) {
        for (int i = 0; i < tableCarga.getRowCount(); i++) {
            tableCarga.removeRow(i);
            i -= 1;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CargaMClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CargaMClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CargaMClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CargaMClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CargaMClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClientes;
    // End of variables declaration//GEN-END:variables
}
