/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import dao.ReportesDAOImpl;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author PRR1TL
 */
public class Reportes extends javax.swing.JFrame {

    /**
     * Creates new form Reportes
     */
    ReportesDAOImpl reportesCosultas = new ReportesDAOImpl();
    
    //DATOS PARA LAS CONSULTAS
    String linea = "";
    String tema = "";
    String cliente = "";
    String fechaInicial = "";
    String fechaFinal = "";
    
    //BANDERAS 
    public int bnProduccion = 0;
    public int bnScrap = 0;
    
    
    // DATOS OBTENIDOS DE LAS CONSULTAS
    int cantidadTotalProduccion = 0 ;
    int cantidadTotalScrap = 0;
    int catidadRegistrosNoParteLinea = 0;
    
    ArrayList<String> cantidadProduccionPorParte ;
    ArrayList<String> listadoProduccionPorParte ;
    
    private final SimpleDateFormat fechaFormato = new SimpleDateFormat("dd/MM/yyyy");
    
    public Reportes() {
        initComponents();
        cmbArea.setVisible(false);
        cmbCliente.setVisible(false);
        dteFechaInicial.setDateFormat(fechaFormato);
        dteFechaFinal.setDateFormat(fechaFormato);
        dteFechaInicial.setDate(new Date(System.currentTimeMillis()));
        dteFechaFinal.setDate(new Date(System.currentTimeMillis()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbTema = new javax.swing.JComboBox<>();
        cmbArea = new javax.swing.JComboBox<>();
        cmbLinea = new javax.swing.JComboBox<>();
        btnGenerar = new javax.swing.JButton();
        dteFechaInicial = new com.alee.extended.date.WebDateField();
        dteFechaFinal = new com.alee.extended.date.WebDateField();
        cmbCliente = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        cmbTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTemaActionPerformed(evt);
            }
        });

        cmbLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLineaActionPerformed(evt);
            }
        });

        btnGenerar.setText("Generar");
        btnGenerar.setEnabled(false);
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        dteFechaInicial.setEnabled(false);
        dteFechaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dteFechaInicialActionPerformed(evt);
            }
        });

        dteFechaFinal.setEnabled(false);
        dteFechaFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dteFechaFinalActionPerformed(evt);
            }
        });

        cmbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(cmbLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(cmbTema, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(cmbArea, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(dteFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dteFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGenerar)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(dteFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGenerar)
                        .addComponent(dteFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            cmbLinea.setModel(reportesCosultas.listaLineasBitacora());            
        } catch (Exception ex) {
            Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void cmbTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTemaActionPerformed
        cantidadTotalProduccion = 0 ;
        cantidadTotalScrap = 0;
        
        //OBTENEMOS DATOS 
        linea = cmbLinea.getSelectedItem().toString();
        fechaInicial = "15/08/2017";
        fechaFinal = "04/09/2017";
        System.out.println(cmbTema.getSelectedIndex());
        
        if (cmbTema.getSelectedIndex() != 0){
            tema  = "Piezas Producidas";
            if (cmbTema.getSelectedIndex() == 1 ){ //Produccion
                tema  = "Piezas Producidas";
                bnProduccion = 1;
                bnScrap = 0;
                try {                    
                    cantidadTotalProduccion = reportesCosultas.produccionTotal(linea, fechaInicial, fechaFinal);
                    cmbCliente.setModel(reportesCosultas.listaClientesProduccion(linea, tema, fechaInicial, fechaFinal));
                    cmbCliente.setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else if (cmbTema.getSelectedIndex() == 2){//Perdidas
                tema = "Piezas Producidas";
                bnProduccion = 0;
                bnScrap = 1;
                try {
                    cantidadTotalScrap = reportesCosultas.scrapTotal(linea, tema, fechaInicial, fechaFinal);
                    cmbCliente.setModel(reportesCosultas.listaClientesScrap(linea, tema, fechaInicial, fechaFinal));
                    cmbCliente.setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (cmbTema.getSelectedIndex() == 3){ //Ambos
                try {
                    cantidadTotalProduccion = reportesCosultas.produccionTotal(linea, fechaInicial, fechaFinal);
                    cantidadTotalScrap = reportesCosultas.scrapTotal(linea, tema, fechaInicial, fechaFinal);
                    cmbCliente.setSelectedIndex(-1);
                    cmbCliente.setVisible(false);
                    cmbArea.setSelectedIndex(-1);
                    cmbArea.setVisible(false);
                } catch (Exception ex) {
                    Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            //dteFechaInicial.setEnabled(true);
        } else {
            cmbArea.setSelectedItem(-1);
            cmbArea.setEnabled(false);
            cmbArea.setVisible(false);
            //dteFechaInicial.setEnabled(false);
        }
        System.out.println("Reporte: \nPiezas Producidas: "+cantidadTotalProduccion+"\nSrap: "+cantidadTotalScrap);
    }//GEN-LAST:event_cmbTemaActionPerformed

    private void dteFechaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dteFechaInicialActionPerformed
        dteFechaFinal.setEnabled(true);
    }//GEN-LAST:event_dteFechaInicialActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        JOptionPane.showMessageDialog(this,"Archivo generado");
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void cmbLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLineaActionPerformed
        if(cmbLinea.getSelectedIndex() != 0){
            String[] tipoConsulta = {"Selecciona Tema", "Piezas Producidas", "Perdidas", "Ambas"};
            DefaultComboBoxModel modelo = new DefaultComboBoxModel(tipoConsulta);
            cmbTema.setEnabled(true);
            cmbTema.setModel(modelo);
        }         
    }//GEN-LAST:event_cmbLineaActionPerformed

    private void dteFechaFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dteFechaFinalActionPerformed
        btnGenerar.setEnabled(true);
    }//GEN-LAST:event_dteFechaFinalActionPerformed

    private void cmbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClienteActionPerformed
        cliente = cmbCliente.getSelectedItem().toString(); 
        if(cmbCliente.getSelectedIndex() != 0){
            if (cmbCliente.getSelectedIndex() == 1){
                try {
                    cmbArea.setModel(reportesCosultas.listaNoParteProduccion(linea, tema, cliente, fechaInicial, fechaFinal));
                    cmbArea.setEnabled(true);
                    cmbArea.setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else if (cmbCliente.getSelectedIndex() == 2){
                try {
                    cmbArea.setModel(reportesCosultas.listaNoParteScrap(linea, tema, cliente, fechaInicial, fechaFinal));
                    cmbArea.setEnabled(true);
                    cmbArea.setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_cmbClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JComboBox<String> cmbArea;
    private javax.swing.JComboBox<String> cmbCliente;
    private javax.swing.JComboBox<String> cmbLinea;
    private javax.swing.JComboBox<String> cmbTema;
    private com.alee.extended.date.WebDateField dteFechaFinal;
    private com.alee.extended.date.WebDateField dteFechaInicial;
    // End of variables declaration//GEN-END:variables
}
