/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import dao.ReportesDAOImpl;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author PRR1TL
 */
public class Reportes extends javax.swing.JFrame {

    /**
     * Creates new form Reportes
     */
    ReportesDAOImpl reportesCosultas = new ReportesDAOImpl();
    
    //DATOS PARA LAS CONSULTAS
    String linea = "";
    String tema = "";
    String cliente = "";
    String noParte = "";
    String fechaInicial = "";
    String fechaFinal = "";
    
    //BANDERAS 
    public int bnProduccion = 0;
    public int bnScrap = 0;
    
    
    // DATOS OBTENIDOS DE LAS CONSULTAS
    int cantidadTotalProduccion = 0 ;
    int cantidadTotalScrap = 0;
    
    //DEVUELVE VALORES DE LA BASE DE DATOS 
    //PRODUCCION
    ArrayList<String> listaClientesGenerales;
    ArrayList<String> listaClienteEspecifico;
    ArrayList<String> listaModelosGenerales;
    ArrayList<String> listaModeloEspecifico;
    ArrayList<String> listaClientesModelosGenerales;
    //PERDIDAS
    ArrayList<String> listaPerdidasGenerales;
    ArrayList<String> listaPerdidaEspecifica;
    ArrayList<String> listaAreasGenerales;
    ArrayList<String> listaAreaEspecifica;
    ArrayList<String> listaPerdidasAreasEspecificas;
    ArrayList<String> listaProblemasGenerales;
    ArrayList<String> listaProblemaEspecifico;
    ArrayList<String> listaPerdidasAreasProblemasGenerales;
    
    
    private final SimpleDateFormat fechaFormato = new SimpleDateFormat("dd/MM/yyyy");
    
    public Reportes() {
        initComponents();
        cmbNoParteArea.setVisible(false);
        cmbClientePerdidas.setVisible(false);
        dteFechaInicial.setDateFormat(fechaFormato);
        dteFechaFinal.setDateFormat(fechaFormato);
        dteFechaInicial.setDate(new Date(System.currentTimeMillis()));
        dteFechaFinal.setDate(new Date(System.currentTimeMillis()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbTema = new javax.swing.JComboBox<>();
        cmbNoParteArea = new javax.swing.JComboBox<>();
        cmbLinea = new javax.swing.JComboBox<>();
        btnGenerar = new javax.swing.JButton();
        dteFechaInicial = new com.alee.extended.date.WebDateField();
        dteFechaFinal = new com.alee.extended.date.WebDateField();
        cmbClientePerdidas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        cmbTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTemaActionPerformed(evt);
            }
        });

        cmbNoParteArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNoParteAreaActionPerformed(evt);
            }
        });

        cmbLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLineaActionPerformed(evt);
            }
        });

        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        dteFechaInicial.setEnabled(false);
        dteFechaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dteFechaInicialActionPerformed(evt);
            }
        });

        dteFechaFinal.setEnabled(false);
        dteFechaFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dteFechaFinalActionPerformed(evt);
            }
        });

        cmbClientePerdidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClientePerdidasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(cmbLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(cmbTema, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(cmbClientePerdidas, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(cmbNoParteArea, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(dteFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dteFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGenerar)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(dteFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbNoParteArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGenerar)
                        .addComponent(dteFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbClientePerdidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            cmbLinea.setModel(reportesCosultas.listaLineasBitacora());            
        } catch (Exception ex) {
            Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void cmbTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTemaActionPerformed
        cantidadTotalProduccion = 0 ;
        cantidadTotalScrap = 0;
        
        //OBTENEMOS DATOS 
        linea = cmbLinea.getSelectedItem().toString();
        fechaInicial = "15/08/2017";
        fechaFinal = "04/09/2017";
        
        if (cmbTema.getSelectedIndex() != 0){
            tema  = "Piezas Producidas";
            if (cmbTema.getSelectedIndex() == 1 ){ //Produccion               
                bnProduccion = 1;
                bnScrap = 0;
                try {                    
                    cantidadTotalProduccion = reportesCosultas.produccionTotal(linea, fechaInicial, fechaFinal);
                    cantidadTotalScrap = 0;
                    cmbClientePerdidas.setModel(reportesCosultas.listaClientesProduccion(linea, tema, fechaInicial, fechaFinal));
                    cmbClientePerdidas.setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else if (cmbTema.getSelectedIndex() == 2){//Perdidas
                bnProduccion = 0;
                bnScrap = 1;
                try {
                    cantidadTotalProduccion = 0;
                    cantidadTotalScrap = reportesCosultas.scrapTotal(linea, fechaInicial, fechaFinal);
                    cmbClientePerdidas.setModel(reportesCosultas.listaClientesScrap(linea, tema, fechaInicial, fechaFinal));
                    cmbClientePerdidas.setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (cmbTema.getSelectedIndex() == 3){ //Ambos
                try {
                    //PRODUCCION
                    cantidadTotalProduccion = reportesCosultas.produccionTotal(linea, fechaInicial, fechaFinal);
                    listaClientesGenerales = reportesCosultas.produccionClientesGeneral(linea, tema, fechaInicial, fechaFinal);
                    listaClientesModelosGenerales = reportesCosultas.produccionClientesModelosGeneral(linea, tema, fechaInicial, fechaFinal);
                    
                    cantidadTotalScrap = reportesCosultas.scrapTotal(linea, fechaInicial, fechaFinal);
                    listaPerdidasGenerales = reportesCosultas.perdidasPorTemaGeneral(linea, tema, fechaInicial, fechaFinal);
                    listaAreasGenerales = reportesCosultas.perdidasPorAreaGeneral(linea, tema, fechaInicial, fechaFinal);
                    listaPerdidasAreasProblemasGenerales = reportesCosultas.perdidasPorTemaAreaProblemaGeneral(linea, tema, fechaInicial, fechaFinal);

                    
                    System.out.println("Reporte: \nPiezas Producidas: "+cantidadTotalProduccion);
                    System.out.println("Clientes Generales: "+listaClientesGenerales);
                    System.out.println("Clientes Modelo Generales: "+listaClientesModelosGenerales);
                    
                    System.err.println("\nSrap: "+cantidadTotalScrap);
                    System.err.println("\nLista Perdidas Generales: "+listaPerdidasGenerales);
                    System.err.println("\nLista Areas Generales: "+listaAreasGenerales);
                    System.err.println("\nLista Peridas, Areas, Problema: "+listaPerdidasAreasProblemasGenerales);
                     
                } catch (Exception ex) {
                    Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
        } else {
            cmbNoParteArea.setSelectedItem(-1);
            cmbNoParteArea.setEnabled(false);
            cmbNoParteArea.setVisible(false);
        }
        
    }//GEN-LAST:event_cmbTemaActionPerformed

    private void dteFechaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dteFechaInicialActionPerformed
        dteFechaFinal.setEnabled(true);
    }//GEN-LAST:event_dteFechaInicialActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        System.out.println("Reporte: \nPiezas Producidas: "+cantidadTotalProduccion);
        System.err.println("Srap: "+cantidadTotalScrap);
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void cmbLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLineaActionPerformed
        if(cmbLinea.getSelectedIndex() != 0){
            String[] tipoConsulta = {"Selecciona Tema", "Piezas Producidas", "Perdidas", "Ambas"};
            DefaultComboBoxModel modelo = new DefaultComboBoxModel(tipoConsulta);
            cmbTema.setEnabled(true);
            cmbTema.setModel(modelo);
        }         
    }//GEN-LAST:event_cmbLineaActionPerformed

    private void dteFechaFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dteFechaFinalActionPerformed
        btnGenerar.setEnabled(true);
    }//GEN-LAST:event_dteFechaFinalActionPerformed

    private void cmbClientePerdidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClientePerdidasActionPerformed
         
        if(cmbClientePerdidas.getSelectedIndex() != 0){
            cliente = cmbClientePerdidas.getSelectedItem().toString();
            if (cmbTema.getSelectedIndex() == 1 ){ //PRODUCCION
                if (cmbClientePerdidas.getSelectedIndex() == 1){ //TODOS 
                    try {
                        listaClientesGenerales = reportesCosultas.produccionClientesGeneral(linea, tema, fechaInicial, fechaFinal);
                        listaClienteEspecifico = new ArrayList<>();
                        cmbNoParteArea.setModel(reportesCosultas.listaNoParteProduccion(linea, tema, cliente, fechaInicial, fechaFinal));
                        cmbNoParteArea.setEnabled(true);
                        cmbNoParteArea.setVisible(true);
                    } catch (Exception ex) {
                        Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }else if (cmbClientePerdidas.getSelectedIndex() == 2){
                    try {
                        listaClientesGenerales = new ArrayList<>();        
                        listaClienteEspecifico = reportesCosultas.produccionClienteEpecifico(linea, tema, cliente, fechaInicial, fechaFinal);
                        cmbNoParteArea.setModel(reportesCosultas.listaNoParteProduccion(linea, tema, cliente, fechaInicial, fechaFinal));
                        cmbNoParteArea.setEnabled(true);
                        cmbNoParteArea.setVisible(true);
                    } catch (Exception ex) {
                        Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } else { //PERDIDAS
                
            }
        }
        System.out.println("Clientes General: "+ listaClientesGenerales); 
        System.out.println("Cliente Especifico ("+cliente+"): "+ listaClienteEspecifico);
    }//GEN-LAST:event_cmbClientePerdidasActionPerformed

    private void cmbNoParteAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNoParteAreaActionPerformed
        if(cmbNoParteArea.getSelectedIndex() != 0){
            noParte = cmbNoParteArea.getSelectedItem().toString();
            if (cmbTema.getSelectedIndex() == 1 ){ //PRODUCCION
                if(cmbNoParteArea.getSelectedIndex() == 1 ){ //TODOS
                    if(cmbClientePerdidas.getSelectedIndex() != 1 ){ // CUANDO NO SE SELECCIONO TODOS EN CLIENTE
                        try {
                            listaModelosGenerales = reportesCosultas.produccionModeloGeneral(linea, tema, cliente, fechaInicial, fechaFinal);
                            listaModeloEspecifico = new ArrayList<>();
                            listaClientesModelosGenerales = new ArrayList<>();
                        } catch (Exception ex) {
                            Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }else{ // CUANDO SE SELECCIONA TODOS EN CLIENTE
                        try {
                            listaModeloEspecifico = new ArrayList<>();
                            listaModelosGenerales = new ArrayList<>();                        
                            listaClientesModelosGenerales = reportesCosultas.produccionClientesModelosGeneral(linea, tema, fechaInicial, fechaFinal);
                        } catch (Exception ex) {
                            Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }else { // NO PARTE SELECCIONADA
                    try {                
                        listaModelosGenerales = new ArrayList<>();
                        listaClientesModelosGenerales = new ArrayList<>();
                        listaModeloEspecifico = reportesCosultas.produccionModeloEpecifico(linea, tema, noParte, fechaInicial, fechaFinal) ;
                    } catch (Exception ex) {
                        Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                System.out.println("Modelos Generales: "+listaModelosGenerales);
                System.out.println("Modelo Especifico ("+noParte+"): "+listaModeloEspecifico);
                System.out.println("Cliente Modelo "+listaClientesModelosGenerales);
            } else { //PERDIDAS
                
            }
        }
        
    }//GEN-LAST:event_cmbNoParteAreaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JComboBox<String> cmbClientePerdidas;
    private javax.swing.JComboBox<String> cmbLinea;
    private javax.swing.JComboBox<String> cmbNoParteArea;
    private javax.swing.JComboBox<String> cmbTema;
    private com.alee.extended.date.WebDateField dteFechaFinal;
    private com.alee.extended.date.WebDateField dteFechaInicial;
    // End of variables declaration//GEN-END:variables
}
