/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author GUR5TL
 */
public class Operaciones extends javax.swing.JDialog {

    String per;

    /**
     * Creates new form
     */
    public Operaciones(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        menuEditar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuEliminar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbTema = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cmbOperacion = new javax.swing.JComboBox();
        cmbArea = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtDescProblema = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDescOpe = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPerdidas = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        cmbBuscar = new javax.swing.JComboBox();

        menuEditar.setText("Editar");
        menuEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(menuEditar);
        jPopupMenu1.add(jSeparator1);

        menuEliminar.setText("Eliminar");
        menuEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEliminarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(menuEliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Oprecion"));

        jLabel2.setText("Operación:");

        cmbTema.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTemaItemStateChanged(evt);
            }
        });

        jLabel3.setText("Tema:");

        cmbOperacion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbOperacionItemStateChanged(evt);
            }
        });

        jLabel4.setText("Problema:");

        jLabel1.setText("Area:");

        jLabel5.setText("Descripcion:");

        txtDescOpe.setEditable(false);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(cmbArea, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(494, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cmbOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDescOpe)
                                        .addContainerGap())
                                    .addComponent(cmbTema, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDescProblema, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(txtDescOpe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDescProblema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablaPerdidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tema", "Operacion", "Area", "Problema"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaPerdidas.setComponentPopupMenu(jPopupMenu1);
        tablaPerdidas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaPerdidas);

        jLabel6.setText("Buscar por:");

        txtBuscar.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtBuscarCaretUpdate(evt);
            }
        });

        cmbBuscar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tema", "Operacion", "Area", "Problema" }));
        cmbBuscar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbBuscarItemStateChanged(evt);
            }
        });
        cmbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Object[] o;
        DefaultTableModel mod = (DefaultTableModel) tablaPerdidas.getModel();
        mod = PrincipalOne.ms.llenaTablaPerdidas(PrincipalOne.cmbLinea.getSelectedItem().toString(), mod);
        tablaPerdidas.setModel(mod);
        cmbTema.setModel(PrincipalOne.cls.ListaTemas());
        TableRowSorter<TableModel> elQueOrdena = new TableRowSorter<TableModel>(mod);
        tablaPerdidas.setRowSorter(elQueOrdena);


    }//GEN-LAST:event_formWindowOpened

    private void cmbTemaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTemaItemStateChanged
        if (cmbTema.getSelectedIndex() > 0) {
            cmbOperacion.setModel(PrincipalOne.cls.ListaOperacionesPorLinea(PrincipalOne.cmbLinea.getSelectedItem().toString()));
        }
    }//GEN-LAST:event_cmbTemaItemStateChanged

    private void cmbOperacionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbOperacionItemStateChanged
        if (cmbOperacion.getSelectedIndex() > 0) {
            cmbArea.setModel(PrincipalOne.cls.ListaAreas(cmbTema.getSelectedItem().toString()));
            txtDescOpe.setText(PrincipalOne.cls.DescOp(PrincipalOne.cmbLinea.getSelectedItem().toString(), cmbOperacion.getSelectedItem().toString()));
        }
    }//GEN-LAST:event_cmbOperacionItemStateChanged

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Object[] regPerdida = new Object[5];
        if (btnGuardar.getText().equals("Guardar")) {
            if (cmbTema.getSelectedIndex() > 0 && cmbOperacion.getSelectedIndex() > 0 && cmbArea.getSelectedIndex() > 0 && !txtDescProblema.getText().equals("")) {
                regPerdida[0] = PrincipalOne.cmbLinea.getSelectedItem().toString();
                regPerdida[1] = cmbTema.getSelectedItem().toString();
                regPerdida[2] = cmbOperacion.getSelectedItem().toString();
                regPerdida[3] = cmbArea.getSelectedItem().toString();
                regPerdida[4] = txtDescProblema.getText();
                PrincipalOne.in.insertaPerdida(regPerdida);
                limpiar();
            } else {
                JOptionPane.showMessageDialog(this, "Se deben llenar todos los campos", "Datos Faltantes", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            regPerdida[0] = PrincipalOne.cmbLinea.getSelectedItem().toString();
            regPerdida[1] = cmbTema.getSelectedItem().toString();
            regPerdida[2] = cmbOperacion.getSelectedItem().toString();
            regPerdida[3] = cmbArea.getSelectedItem().toString();
            regPerdida[4] = txtDescProblema.getText();
            PrincipalOne.in.updatePerdida(this, regPerdida, per);
            btnGuardar.setText("Guardar");
            limpiar();
        }
        DefaultTableModel mod = (DefaultTableModel) tablaPerdidas.getModel();
        mod = PrincipalOne.ms.llenaTablaPerdidas(PrincipalOne.cmbLinea.getSelectedItem().toString(), mod);
        tablaPerdidas.setModel(mod);
        cmbTema.setModel(PrincipalOne.cls.ListaTemas());
        TableRowSorter<TableModel> elQueOrdena = new TableRowSorter<TableModel>(mod);
        tablaPerdidas.setRowSorter(elQueOrdena);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void menuEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditarActionPerformed
        if (tablaPerdidas.getSelectedRow() >= 0) {
            Object[] reg = new Object[tablaPerdidas.getColumnCount()];
            int row = tablaPerdidas.getSelectedRow();
            for (int i = 0; i < tablaPerdidas.getColumnCount(); i++) {
                reg[i] = tablaPerdidas.getValueAt(row, i);
            }
            for (int i = 0; i < cmbTema.getItemCount(); i++) {
                if (cmbTema.getItemAt(i).toString().toLowerCase().equals(reg[0].toString().toLowerCase())) {
                    cmbTema.setSelectedIndex(i);
                }
            }
            for (int i = 0; i < cmbOperacion.getItemCount(); i++) {
                if (cmbOperacion.getItemAt(i).toString().toLowerCase().equals(reg[1].toString().toLowerCase())) {
                    cmbOperacion.setSelectedIndex(i);
                }
            }
            for (int i = 0; i < cmbArea.getItemCount(); i++) {
                if (cmbArea.getItemAt(i).toString().toLowerCase().equals(reg[2].toString().toLowerCase())) {
                    cmbArea.setSelectedIndex(i);
                }
            }
            txtDescProblema.setText(reg[3].toString());
            per = reg[3].toString();
            btnGuardar.setText("Actualizar");
            cmbTema.setEnabled(false);
            cmbOperacion.setEnabled(false);
            cmbArea.setEnabled(false);

        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un registro");
        }
    }//GEN-LAST:event_menuEditarActionPerformed

    private void cmbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBuscarActionPerformed

    private void cmbBuscarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbBuscarItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBuscarItemStateChanged

    private void txtBuscarCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtBuscarCaretUpdate
        tablaPerdidas.setModel(PrincipalOne.cls.busqueda(PrincipalOne.cmbLinea.getSelectedItem().toString(), cmbBuscar.getSelectedItem().toString(),
                txtBuscar.getText(), (DefaultTableModel) tablaPerdidas.getModel()));
    }//GEN-LAST:event_txtBuscarCaretUpdate

    private void menuEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEliminarActionPerformed
        if (tablaPerdidas.getSelectedRow() >= 0) {
            PrincipalOne.mod = 3;
            Login lo = new Login(new javax.swing.JDialog(), true);
            lo.setVisible(true);
            if (Login.resp == 1) {
                int op = JOptionPane.showConfirmDialog(this, "El registro se eliminará permanentemente\n ¿Desea Continar?", "Precaucion", JOptionPane.WARNING_MESSAGE);
                if (op == 0) {
                    Object[] reg = new Object[tablaPerdidas.getColumnCount()];
                    int row = tablaPerdidas.getSelectedRow();
                    for (int i = 0; i < tablaPerdidas.getColumnCount(); i++) {
                        reg[i] = tablaPerdidas.getValueAt(row, i);
                    }
                    PrincipalOne.in.deletePerdida(this, reg, PrincipalOne.cmbLinea.getSelectedItem().toString());
                    DefaultTableModel mod = (DefaultTableModel) tablaPerdidas.getModel();
                    mod = PrincipalOne.ms.llenaTablaPerdidas(PrincipalOne.cmbLinea.getSelectedItem().toString(), mod);
                    tablaPerdidas.setModel(mod);
                    cmbTema.setModel(PrincipalOne.cls.ListaTemas());
                    TableRowSorter<TableModel> elQueOrdena = new TableRowSorter<TableModel>(mod);
                    tablaPerdidas.setRowSorter(elQueOrdena);
                }
            }
        }
    }//GEN-LAST:event_menuEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed
    
    public void limpiar() {
        cmbTema.setSelectedIndex(0);
        cmbOperacion.setSelectedIndex(-1);
        cmbArea.setSelectedIndex(-1);
        txtDescOpe.setText("");
        txtDescProblema.setText("");
        cmbTema.setEnabled(true);
        cmbOperacion.setEnabled(true);
        cmbArea.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox cmbArea;
    private javax.swing.JComboBox cmbBuscar;
    private javax.swing.JComboBox cmbOperacion;
    private javax.swing.JComboBox cmbTema;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menuEditar;
    private javax.swing.JMenuItem menuEliminar;
    private javax.swing.JTable tablaPerdidas;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtDescOpe;
    private javax.swing.JTextField txtDescProblema;
    // End of variables declaration//GEN-END:variables
}
