/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Clases.Consultas;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author GUR5TL
 */
public class TiemposPromedio extends javax.swing.JDialog {

    static Consultas cls;
    DefaultComboBoxModel mod = new DefaultComboBoxModel();

    /**
     * Creates new form TiemposPromedio
     */
    public TiemposPromedio(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        cls = new Consultas();
        txtPzasPorTurno.setEditable(false);
        txtDuracionTurno.setEditable(false);
        txtPzsHora.setEditable(false);
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/sg.jpg")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTcPromedio = new javax.swing.JTextField();
        txtNoPersonas = new javax.swing.JTextField();
        comboLineas = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        comboTurnos = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtDuracionTurno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPzsHora = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtPzasPorTurno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administrar Tiempos Ciclo");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de Linea", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel1.setText("Linea");

        jLabel3.setText("No. de Personas:");

        jLabel5.setText("T.C. promedio:");

        txtTcPromedio.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                txtTcPromedioComponentAdded(evt);
            }
        });
        txtTcPromedio.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTcPromedioCaretUpdate(evt);
            }
        });
        txtTcPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTcPromedioActionPerformed(evt);
            }
        });
        txtTcPromedio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTcPromedioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTcPromedioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTcPromedioKeyTyped(evt);
            }
        });

        comboLineas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboLineasActionPerformed(evt);
            }
        });

        jLabel2.setText("Turno:");

        comboTurnos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-------------------", "Uno", "Dos", "Tres" }));
        comboTurnos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboTurnosItemStateChanged(evt);
            }
        });
        comboTurnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTurnosActionPerformed(evt);
            }
        });

        jLabel4.setText("Duracion de Turno:");

        txtDuracionTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDuracionTurnoActionPerformed(evt);
            }
        });

        jLabel6.setText("Pzas. por Hora:");

        txtPzsHora.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                txtPzsHoraCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtPzsHoraInputMethodTextChanged(evt);
            }
        });
        txtPzsHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPzsHoraActionPerformed(evt);
            }
        });
        txtPzsHora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPzsHoraKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPzsHoraKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPzsHoraKeyTyped(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jLabel7.setText("pzas. por Turno:");

        txtPzasPorTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPzasPorTurnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTcPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPzsHora, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboLineas, 0, 143, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(comboTurnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNoPersonas, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDuracionTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPzasPorTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDuracionTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(comboLineas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNoPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(comboTurnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTcPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtPzsHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtPzasPorTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(75, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnActualizar)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDuracionTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDuracionTurnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDuracionTurnoActionPerformed

    private void comboLineasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboLineasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboLineasActionPerformed

    private void comboTurnosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboTurnosItemStateChanged
        Object[] datos;
        if (comboTurnos.getSelectedIndex() > 0) {
            datos = cls.buscaTiempoLiena(comboLineas.getSelectedItem().toString(), comboTurnos.getSelectedIndex());
            if (datos[0] != null) {
                txtNoPersonas.setText(datos[0].toString());
                txtDuracionTurno.setText(datos[1].toString());
                txtTcPromedio.setText(datos[2].toString());
                txtPzsHora.setText(datos[3].toString());
                float pzas = 0;
                if (!txtPzsHora.getText().equals("") && !txtDuracionTurno.getText().equals("")) {
                    pzas = Float.parseFloat(txtPzsHora.getText()) * Float.parseFloat(txtDuracionTurno.getText());
                    txtPzasPorTurno.setText(String.valueOf(pzas));
                }
            }
        }


    }//GEN-LAST:event_comboTurnosItemStateChanged

    private void comboTurnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTurnosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTurnosActionPerformed

    private void txtPzsHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPzsHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPzsHoraActionPerformed

    private void txtPzsHoraInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtPzsHoraInputMethodTextChanged

    }//GEN-LAST:event_txtPzsHoraInputMethodTextChanged

    private void txtPzsHoraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPzsHoraKeyPressed

    }//GEN-LAST:event_txtPzsHoraKeyPressed

    private void txtPzsHoraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPzsHoraKeyReleased


    }//GEN-LAST:event_txtPzsHoraKeyReleased

    private void txtPzsHoraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPzsHoraKeyTyped
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9')) {
            if ((car != '.')) {
                evt.consume();
            }
        }
        if (txtPzsHora.getText().length() >= 6) {
            evt.consume();
        }        // TODO add your handling code here:
        if (car == '.' && txtPzsHora.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPzsHoraKeyTyped

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        if (!txtNoPersonas.getText().equals("") && !txtPzsHora.getText().equals("") && !txtTcPromedio.getText().equals("")
                && comboTurnos.getSelectedIndex() != 0 && comboLineas.getSelectedIndex() != 0) {
            Object[] datos = new Object[7];
            datos[0] = comboLineas.getSelectedItem().toString();
            datos[1] = comboTurnos.getSelectedIndex();
            datos[2] = txtNoPersonas.getText();
            datos[3] = txtDuracionTurno.getText();
            datos[4] = txtTcPromedio.getText();
            datos[5] = txtPzsHora.getText();
            datos[6] = txtPzasPorTurno.getText();
            cls.actualizaTiemposLinea(datos);
            JOptionPane.showMessageDialog(this, "Actualizacion Correcta");
            comboLineas.setSelectedIndex(0);
            comboTurnos.setSelectedIndex(0);
            txtNoPersonas.setText("");
            txtDuracionTurno.setText("");
            txtTcPromedio.setText("");
            txtPzsHora.setText("");
            txtPzasPorTurno.setText("");

        } else {
            JOptionPane.showMessageDialog(this, "Debe llenar todos los campos", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        comboLineas.setSelectedIndex(0);
        comboTurnos.setSelectedIndex(0);
        txtNoPersonas.setText("");
        txtDuracionTurno.setText("");
        txtTcPromedio.setText("");
        txtPzsHora.setText("");
        txtPzasPorTurno.setText("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtPzasPorTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPzasPorTurnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPzasPorTurnoActionPerformed

    private void txtTcPromedioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTcPromedioKeyPressed

    }//GEN-LAST:event_txtTcPromedioKeyPressed

    private void txtTcPromedioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTcPromedioKeyTyped
        char car = evt.getKeyChar();
        if (txtTcPromedio.getText().equals("")) {
            if ((car < '1' || car > '9')) {
                evt.consume();
            }
        } else {
            if ((car < '0' || car > '9')) {
                if ((car != '.')) {
                    evt.consume();
                }
            }
            if (txtTcPromedio.getText().length() >= 6) {
                evt.consume();
            }        // TODO add your handling code here:
            if (car == '.' && txtTcPromedio.getText().contains(".")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtTcPromedioKeyTyped

    private void txtPzsHoraCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtPzsHoraCaretPositionChanged

    }//GEN-LAST:event_txtPzsHoraCaretPositionChanged

    private void txtTcPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTcPromedioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTcPromedioActionPerformed

    private void txtTcPromedioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTcPromedioKeyReleased

    }//GEN-LAST:event_txtTcPromedioKeyReleased

    private void txtTcPromedioComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_txtTcPromedioComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTcPromedioComponentAdded

    private void txtTcPromedioCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTcPromedioCaretUpdate
        float pzas = 0;

        if (!txtTcPromedio.getText().equals("") && !txtDuracionTurno.getText().equals("")) {
            pzas = 3600 / Float.parseFloat(txtTcPromedio.getText());
            txtPzsHora.setText(String.valueOf(pzas));
        }
        float pzas2 = 0;
        if (!txtPzsHora.getText().equals("") && !txtDuracionTurno.getText().equals("")) {
            pzas2 = Float.parseFloat(txtPzsHora.getText()) * Float.parseFloat(txtDuracionTurno.getText());
            txtPzasPorTurno.setText(String.valueOf(pzas2));
        }
    }//GEN-LAST:event_txtTcPromedioCaretUpdate

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Object[] obj;
        ArrayList li = PrincipalOne.cls.Lineas();
        for (int i = 0; i < li.size(); i++) {
            obj = (Object[]) li.get(i);
            mod.addElement(obj[0]);
        }
        comboLineas.setModel(mod);
    }//GEN-LAST:event_formWindowOpened

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TiemposPromedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TiemposPromedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TiemposPromedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TiemposPromedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                TiemposPromedio dialog = new TiemposPromedio(new javax.swing.JDialog(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox comboLineas;
    private javax.swing.JComboBox comboTurnos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDuracionTurno;
    private javax.swing.JTextField txtNoPersonas;
    private javax.swing.JTextField txtPzasPorTurno;
    private javax.swing.JTextField txtPzsHora;
    private javax.swing.JTextField txtTcPromedio;
    // End of variables declaration//GEN-END:variables
}
